### ISSUE TITLE
FECHA VACIA

### ISSUE THREAD

**Issue by benrojas01** [Irwin1985/BlackFox#1]
estimado Irwin,

de antemano, gracias por tus maravillosos aportes, resulta que estoy comunicandome con una API, pero cuando recupero los datos necesito grabarlos en una tabla, pero el valor de la fecha me lo muestra vacio   (  /   /      )

Agradezco que por favor me expliques como puedo solucionarlo

gracias
![Captura_blackfox](https://user-images.githubusercontent.com/32991065/119206387-a0109480-ba60-11eb-8479-4c7fccf5a461.PNG)

**Comment by Irwin1985** [comment]
Hola, puedes enviarme la respuesta de la petición para hacer pruebas?

**Comment by benrojas01** [comment]
buenas noches Irwin,

el problema es el siguiente:

cuando envió la petición a través de Blackfox y recibo la respuesta,
procedo  a parsear el objeto  (MyHTTP.responseText) con Jsonfox de la
siguiente manera:

xobjvfp = _screen.json.parse(MyHTTP.responseText)
? xobjvfp

al imprimir los datos en el _screen, todo está correcto y la fecha de
expiración se muestra normal
[image: image.png]


luego de ello, quiero utilizar los datos para guardarlos en una tabla,
procedo a ejecutar el procedimiento encode y decode para convertir a un
objeto foxpro, a continuación, quiero enviar los datos a una variable para
insertarla en la tabla y allí es cuando la fecha la trae vacía

jobjvfp = _screen.json.encode(xobjvfp)

sobjvfp = _screen.json.decode(jobjvfp)

m.name = sobjvfp.name
m.logo = sobjvfp.logo
m.expires = sobjvfp.expires_at

?m.name
?m.logo
?m.expires

este es el resultado que me muestra

[image: image.png]


Adjunto envío el programa que hace la petición por si quieres probarlo

saludos y muchas gracias por tu ayuda


adjunto envío el programa que envía la petición

**Comment by Irwin1985** [comment]
Vale ya entiendo, de casualidad estás probando con la última versión de JSONFox? te la puedes descargar [aquí](https://github.com/Irwin1985/JSONFox/blob/master/jsonfox.app):

**Comment by benrojas01** [comment]
Buenos días Irwin.

Definitivamente con la nueva versión funciona correctamente

TE agradezco mucho la ayuda

Por otra parte, me gustaría saber si es posible que puedas darme una
asesoría personalizada *(tú me indicas valor de tus honorarios por hora) *,
ya que estoy implementando unos proyectos web con foxpro y utilizando tus
herramientas, pero me gustaría entender algunas cosas que necesito y que
pienso que puedo hacer con tus aportes.

quedo atento a tus comentarios

saludos,

**Comment by Irwin1985** [comment]
Me alegra que te haya servido, claro que si amigo. Reúneme tus dudas y me las envías por email a <rodriguez.irwin@gmail.com> para analizarlas y ver si está en mis capacidades el poder ayudarte. Saludos!
